"""Integration test for FR-01: extract the committed synthetic Juice Shop report.

Reads the real fixture binary (``tests/data/juice_shop_report_synthetic.pdf``,
regenerated by ``scripts/gen_fixture_pdf.py``) end to end through PyMuPDF4LLM.
Marked ``integration`` because it touches a file and the PDF stack rather than
being pure logic. FR-01 now produces whole-document Markdown in one pass — no
heading segmentation (ADR-0047) — so the checks are on the report text itself.
"""

from pathlib import Path

import pytest

from revalid.pdf import read_pdf

pytestmark = pytest.mark.integration

FIXTURE = Path(__file__).parents[1] / "data" / "juice_shop_report_synthetic.pdf"

EXPECTED_FINDINGS = [
    "Finding 1 — SQL Injection in Login Form",
    "Finding 2 — Reflected Cross-Site Scripting in Search",
    "Finding 3 — Broken Access Control on Basket",
    "Finding 4 — Verbose Error Messages Expose Stack Traces",
]


def test_fixture_extracts_all_findings() -> None:
    report = read_pdf(FIXTURE.read_bytes())
    assert report.page_count == 2
    # Every finding's heading survives in the whole-document Markdown the LLM reads.
    for title in EXPECTED_FINDINGS:
        assert title in report.text


def test_table_borne_metadata_survives_extraction() -> None:
    # Finding 1's severity/CWE/endpoint are rendered as a table in the PDF;
    # they must still reach the Markdown (FR-01 table tolerance).
    report = read_pdf(FIXTURE.read_bytes())
    for token in ("Critical", "CWE-89", "/rest/user/login"):
        assert token in report.text


def test_reproduction_payload_preserved() -> None:
    report = read_pdf(FIXTURE.read_bytes())
    # The SQLi reproduction payload must survive verbatim for FR-03/FR-04.
    assert "' OR 1=1--" in report.text
