"""Integration test for FR-01: extract the committed synthetic Juice Shop report.

Reads the real fixture binary (``tests/data/juice_shop_report_synthetic.pdf``,
regenerated by ``scripts/gen_fixture_pdf.py``) end to end through pdfplumber.
Marked ``integration`` because it touches a file and the PDF stack rather than
being pure logic.
"""

import zlib
from pathlib import Path

import pytest

from revalid.pdf import PdfError, read_pdf, segment_findings

pytestmark = pytest.mark.integration

FIXTURE = Path(__file__).parents[1] / "data" / "juice_shop_report_synthetic.pdf"

EXPECTED_HEADINGS = [
    "Finding 1 — SQL Injection in Login Form",
    "Finding 2 — Reflected Cross-Site Scripting in Search",
    "Finding 3 — Broken Access Control on Basket",
    "Finding 4 — Verbose Error Messages Expose Stack Traces",
]


def test_fixture_extracts_all_findings() -> None:
    report = read_pdf(FIXTURE.read_bytes())
    assert report.page_count == 2

    candidates = segment_findings(report)
    assert [c.heading for c in candidates] == EXPECTED_HEADINGS


def test_table_borne_metadata_survives_extraction() -> None:
    # Finding 1's severity/CWE/endpoint are rendered as a table in the PDF;
    # they must still reach the text (FR-01 table tolerance).
    [finding_one, *_] = segment_findings(read_pdf(FIXTURE.read_bytes()))
    for token in ("Critical", "CWE-89", "/rest/user/login"):
        assert token in finding_one.text


def test_reproduction_payload_preserved() -> None:
    report = read_pdf(FIXTURE.read_bytes())
    # The SQLi reproduction payload must survive verbatim for FR-03/FR-04.
    assert "' OR 1=1--" in report.text


def _decompression_bomb(expanded_chars: int) -> bytes:
    """A tiny PDF whose one Flate stream expands to ``expanded_chars`` of text."""
    raw = b"BT /F1 12 Tf 72 720 Td (" + b"A" * expanded_chars + b") Tj ET"
    comp = zlib.compress(raw)
    objs = [
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n",
        b"4 0 obj\n<< /Length %d /Filter /FlateDecode >>\nstream\n%s\nendstream\nendobj\n"
        % (len(comp), comp),
        b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    ]
    pdf = b"%PDF-1.4\n"
    offsets = []
    for obj in objs:
        offsets.append(len(pdf))
        pdf += obj
    xref_pos = len(pdf)
    size = len(objs) + 1
    xref = b"xref\n0 %d\n0000000000 65535 f \n" % size
    for off in offsets:
        xref += b"%010d 00000 n \n" % off
    pdf += xref
    pdf += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (size, xref_pos)
    return pdf


def test_extraction_deadline_rejects_bomb(monkeypatch: pytest.MonkeyPatch) -> None:
    # A single crafted page expands to ~11 MiB of glyphs and hangs pdfminer's
    # layout analysis; the wall-clock deadline must convert that into a PdfError
    # (empirically it ran > 2 minutes before this guard existed).
    monkeypatch.setattr("revalid.pdf._MAX_EXTRACT_SECONDS", 2.0)
    with pytest.raises(PdfError, match="timed out"):
        read_pdf(_decompression_bomb(11 * 2**20))
